# Generated by Django 6.1.1 on 2026-09-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_chatsession_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='conversation_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
