# Generated by Django 6.1.1 on 2026-09-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_chatsession_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='embedding',
            name='location_kind',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='embedding',
            name='location_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='embedding',
            name='location_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='source_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
