# Generated by Django 6.1.1 on 2026-09-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_embedding_file_name_embedding_location_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
