"""Generate a few starter questions for a course, drawn from its own content.

Shown to a student on the ask page so they are not staring at a blank box.
Questions are generated by the LLM from the course's lessons and a few excerpts,
and cached until the course's content changes.
"""

from django.conf import settings
from openai import OpenAI

from courses.models import Embedding, Lesson


MODEL = "gemini-3.1-flash-lite"
_cache = {}   # key "<course_id>:<chunk_count>" -> list[str]


def suggest_questions(course_id: str, n: int = 4) -> list[str]:
    """Return up to n starter questions for the course (or [] if empty)."""
    count = Embedding.objects.filter(course_id=course_id).count()
    if count == 0:
        return []   # nothing ingested yet, so nothing to suggest

    # Cache key includes the chunk count, so it refreshes when materials change.
    key = f"{course_id}:{count}"
    if key in _cache:
        return _cache[key]

    lessons = list(Lesson.objects.filter(unit__course_id=course_id)
                   .values_list("name", flat=True)[:12])
    snippets = list(Embedding.objects.filter(course_id=course_id)
                    .values_list("chunk_text", flat=True)[:6])
    context = ("Lessons: " + ", ".join(lessons) + "\n\nExcerpts:\n"
               + "\n---\n".join(s[:300] for s in snippets))
    prompt = (
        f"You are helping students explore a course. From the course content below, write {n} short, "
        f"natural questions a student might ask, each clearly answerable from this content. "
        f"Return exactly one question per line, with no numbering or bullets.\n\n{context}")

    questions = []
    if settings.GEMINI_API_KEY:
        try:
            client = OpenAI(api_key=settings.GEMINI_API_KEY, base_url=settings.GEMINI_BASE_URL)
            resp = client.chat.completions.create(
                model=MODEL, messages=[{"role": "user", "content": prompt}], temperature=0.4)
            for line in resp.choices[0].message.content.splitlines():
                q = line.strip().lstrip("-*0123456789.) ").strip()
                if q:
                    questions.append(q)
        except Exception:
            questions = []

    # Fallback if the model is unavailable or returns nothing: template from lessons.
    if not questions:
        questions = [f"What is covered in {name}?" for name in lessons]

    questions = questions[:n]
    _cache[key] = questions
    return questions
